services:
  scrapper:
    image: ghcr.io/t-dat-901-msc-2026-par-1/scrapper-gabriel:main
    env_file: .env
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - kafka_kafka

volumes:
  venv:

networks:
  kafka_kafka:
    external: true
