import os

MARKETS = [
    "ABCC",
    "alphaex",
    "ascendex",
    "bequant",
    "Bgogo",
    "Bibox",
    "BigONE",
    "bilaxy",
    "Binance",
    "binanceusa",
    "bingx",
    "bit",
    "bit2me",
    "bitbns",
    "bitci",
    "BitexBook",
    "bitfex",
    "Bitfinex",
    "Bitforex",
    "bitget",
    "bithumbglobal",
    "BitMart",
    "Bitmex",
    "bitopro",
    "bitpanda",
    "bitrue",
    "Bitso",
    "Bitstamp",
    "BitTrex",
    "bitunix",
    "bkex",
    "Bleutrade",
    "blockchaincom",
    "BTCAlpha",
    "btcex",
    "BTCMarkets",
    "BTCTurk",
    "btse",
    "bullish",
    "bwexchange",
    "bybit",
    "bydfi",
    "Cexio",
    "Coinbase",
    "CoinDeal",
    "CoinEx",
    "CoinFalcon",
    "coinfield",
    "CoinJar",
    "Coinmate",
    "Coinsbit",
    "coinspro",
    "CoinTiger",
    "coinw",
    "coss",
    "crex24",
    "cryptodotcom",
    "cryptology",
    "Cryptopia",
    "currency",
    "deribit",
    "DigiFinex",
    "Exmo",
    "fastex",
    "FCoin",
    "flipster",
    "Foxbit",
    "ftx",
    "ftxus",
    "garantex",
    "Gateio",
    "Gemini",
    "Graviex",
    "hashkey",
    "HitBTC",
    "HuobiPro",
    "indodax",
    "indoex",
    "Kraken",
    "Kucoin",
    "Kuna",
    "LAToken",
    "LBank",
    "Liqnet",
    "Liquid",
    "Luno",
    "Lykke",
    "MercadoBitcoin",
    "mercatox",
    "mexc",
    "mock",
    "nominex",
    "OKCoin",
    "OKEX",
    "onetrading",
    "osl",
    "P2PB2B",
    "paramountdax",
    "paribu",
    "phemex",
    "Poloniex",
    "probit",
    "safetrade",
    "sigenpro",
    "TheRockTrading",
    "timex",
    "Tokenomy",
    "toobit",
    "tradeogre",
    "Unocoin",
    "Upbit",
    "valr",
    "vitex",
    "wazirx",
    "whitebit",
    "woo",
    "xcoex",
    "xtpub",
    "yellow",
    "Yobit",
    "zbdotcom",
    "ZBG",
    "zebitex",
    "zonda",
]


def get_channel(market: str) -> str:
    base = os.environ.get("BASE").upper()
    quote = os.environ.get("QUOTE").upper()
    return f"0~{market}~{base}~{quote}"


def get_request():
    # `map` returns an iterator in Python 3 which is not JSON serialisable.
    # Convert to a list so json.dumps can encode it on the caller side.
    channels = list(map(get_channel, MARKETS))
    request = {"action": "SubAdd", "subs": channels}
    return request
